[project]
name = "jim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ale-py>=0.11.2",
    "gymnasium[box2d,classic-control]>=1.2.0",
    "ruff>=0.12.10",
]
